import {
  NoteItemAttributes,
  RentalType,
  Structure,
  EvaluationFactor,
} from '../Interfaces';

const initialState: NoteItemAttributes[] = [
  {
    key: '0',
    address: '용현동 1-1',
    deposit: 50000000,
    floor: 3,
    roofFloor: 5,
    map: null,
    monthlyFee: 0,
    photoUri: ['uri'],
    rentalType: RentalType.Rental,
    size: 7,
    agentName: 'A공인중개사사무소',
    agentTel: '010-1234-1234',
    sturctureEvaluationFactors: [
      new EvaluationFactor('엘레베이터', ['있음', '없음']),
      new EvaluationFactor('주차', ['가능', '불가'], 1),
      new EvaluationFactor('방향', ['북향', '동향', '남향', '서향'], 2),
      new EvaluationFactor('채광', ['양호', '미흡']),
    ],
    environmentEvaluationFactors: [
      new EvaluationFactor('수압', ['양호', '미흡'], 1),
      new EvaluationFactor('해충유무', ['양호', '미흡']),
      new EvaluationFactor('누수', ['양호', '미흡']),
      new EvaluationFactor('인테리어', ['양호', '미흡'], 1),
      new EvaluationFactor('방음', ['양호', '미흡']),
      new EvaluationFactor('방범', ['양호', '미흡'], 1),
    ],
    managementFee: 3,
    roomStructure: Structure.OneOpen,
    memo: '',
    options: [
      {name: '에어컨', available: true},
      {name: '냉장고', available: true},
      {name: '세탁기', available: false},
      {name: '가스레인지', available: true},
      {name: '인덕션', available: true},
      {name: '전자레인지', available: true},
      {name: '책상', available: false},
      {name: '책장', available: true},
      {name: '침대', available: false},
      {name: '옷장', available: true},
      {name: '신발장', available: true},
      {name: '싱크대', available: false},
    ],
  },
  {
    key: '1',
    address: '용현동 1-2',
    deposit: 5000000,
    floor: 4,
    map: null,
    monthlyFee: 4000000,
    photoUri: ['uri'],
    rentalType: RentalType.RentalMontlyFee,
    size: 5,
    agentName: 'B공인중개사사무소',
    agentTel: '010-1234-1234',
    sturctureEvaluationFactors: [
      new EvaluationFactor('엘레베이터', ['있음', '없음']),
      new EvaluationFactor('주차', ['가능', '불가'], 1),
      new EvaluationFactor('방향', ['북향', '동향', '남향', '서향'], 2),
      new EvaluationFactor('채광', ['양호', '미흡']),
    ],
    environmentEvaluationFactors: [
      new EvaluationFactor('수압', ['양호', '미흡'], 1),
      new EvaluationFactor('해충유무', ['양호', '미흡']),
      new EvaluationFactor('누수', ['양호', '미흡']),
      new EvaluationFactor('인테리어', ['양호', '미흡'], 1),
      new EvaluationFactor('방음', ['양호', '미흡']),
      new EvaluationFactor('방범', ['양호', '미흡'], 1),
    ],
    managementFee: 0,
    roomStructure: Structure.OneOpen,
    memo: '용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다. 용현동 1-2 메모입니다.',
    options: [
      {name: '에어컨', available: true},
      {name: '냉장고', available: true},
      {name: '세탁기', available: false},
      {name: '가스레인지', available: true},
      {name: '인덕션', available: true},
      {name: '전자레인지', available: true},
      {name: '책상', available: false},
      {name: '책장', available: true},
      {name: '침대', available: false},
      {name: '옷장', available: true},
      {name: '신발장', available: true},
      {name: '싱크대', available: false},
    ],
  },
  {
    key: '2',
    address: '용현동 1-3',
    deposit: 80000000,
    floor: 1,
    map: null,
    monthlyFee: 0,
    photoUri: ['uri'],
    rentalType: RentalType.Trading,
    size: 9,
    agentName: 'C공인중개사사무소',
    agentTel: '010-1234-1234',
    sturctureEvaluationFactors: [
      new EvaluationFactor('엘레베이터', ['있음', '없음']),
      new EvaluationFactor('주차', ['가능', '불가'], 1),
      new EvaluationFactor('방향', ['북향', '동향', '남향', '서향'], 2),
      new EvaluationFactor('채광', ['양호', '미흡']),
    ],
    environmentEvaluationFactors: [
      new EvaluationFactor('수압', ['양호', '미흡'], 1),
      new EvaluationFactor('해충유무', ['양호', '미흡']),
      new EvaluationFactor('누수', ['양호', '미흡']),
      new EvaluationFactor('인테리어', ['양호', '미흡'], 1),
      new EvaluationFactor('방음', ['양호', '미흡']),
      new EvaluationFactor('방범', ['양호', '미흡'], 1),
    ],
    managementFee: 0,
    roomStructure: Structure.Two,
    memo: '용현동1-3 메모입니다.',
    options: [
      {name: '에어컨', available: true},
      {name: '냉장고', available: true},
      {name: '세탁기', available: false},
      {name: '가스레인지', available: true},
      {name: '인덕션', available: true},
      {name: '전자레인지', available: true},
      {name: '책상', available: false},
      {name: '책장', available: true},
      {name: '침대', available: false},
      {name: '옷장', available: true},
      {name: '신발장', available: true},
      {name: '싱크대', available: false},
    ],
  },
];

export default initialState;
